#!/bin/bash
root=$(dirname $0 2>/dev/null)
sudo=$(which sudo 2>/dev/null)
whoami=$(whoami 2>/dev/null)
arch=$(uname -i 2>/dev/null)
dpkg=$(which dpkg 2>/dev/null)
rpm=$(which rpm 2>/dev/null)
#product='cobol'

prereqsCommand=''
prereqsUpgrade=''
runtimeInstallCommand=''
smpRuntimeInstallCommand=''
licenseInstallCommand=''
installCommand=''

#set -e

if ( [ "$sudo" = '' ] && [ "$whoami" != 'root' ] ); then
  echo "Unable to install unless you are root, or 'sudo' is available in your PATH"
  exit 1
fi
if [ "$arch" = 'unknown' ]; then
  arch=$(uname -m 2>/dev/null)
fi
if ( [ "$arch" = 'x86_64' ] ); then
  pkgList=''
  ID_LIKE=''
  if   grep -iE '^ID(_LIKE)?=' /etc/os-release 2>/dev/null | grep -iE 'ubuntu|debian' >/dev/null 2>&1; then
    ID_LIKE='ubuntu'
#  elif grep -iE '^ID(_LIKE)?=' /etc/os-release 2>/dev/null | grep -iE 'sles|suse' >/dev/null 2>&1; then
#    ID_LIKE='sles'
  elif grep -iE '^ID(_LIKE)?=' /etc/os-release 2>/dev/null | grep -iE 'rhel|fedora|centos' >/dev/null 2>&1; then
    ID_LIKE='rhel'
  elif [ "$dpkg" != '' ]; then
    ID_LIKE='ubuntu'
  elif [ "$rpm" != '' ]; then
    ID_LIKE='rhel'
  fi

  if [ "$ID_LIKE" = 'ubuntu' ]; then
    prereqsUpgrade="$sudo dpkg --add-architecture i386 && $sudo apt-get update"
    prereqsPrefix="$sudo apt-get install -y --no-upgrade"
    pkgList='perl gcc-multilib libc6:i386 libc6-dev:i386 libgcc1:i386 libstdc++6:i386 libquadmath0:i386'
    installCommand="$sudo dpkg -iG $root/images/ubuntu/*.deb"
  elif [ "$ID_LIKE" = 'rhel' ]; then
    yum=$(which yum 2>/dev/null)
    if [ "$yum" = '' ]; then
      #use dnf if yum does not exist
      yum='dnf'
    fi
    prereqsUpgrade="$sudo $yum upgrade libstdc++ libgcc"
    prereqsPrefix="$sudo $yum -y install"
    prereqsCommand="libgcc.i686 libstdc++.i686" # need to install these always, just so the install command isn't empty
    pkgList='perl gcc glibc.i686 glibc-devel.i686 libquadmath.i686'
    installCommand="$sudo rpm -Uvh $root/images/rhel/*.rpm"
  fi
  
  #only install missing prerequisites
  if [ "$pkgList" != '' ]; then
    for pkg in $pkgList
    do
      if [ "$dpkg" != '' ]; then
        LANG=en_US dpkg-query --show --showformat='${db:Status-Abbrev}\n' $pkg 2>&1 | grep -vE '^.i' >/dev/null 2>&1
      else
        LANG=en_US rpm -q $pkg 2>/dev/null | grep 'not installed$' >/dev/null 2>&1
      fi
      if [ $? -eq 0 ]; then
        prereqsCommand="$prereqsCommand $pkg"
      fi
    done
  fi
fi  

if [ "$installCommand" = '' ]; then
  echo 'Unable to determine the installation command based on the architecture and distribution'
  echo 'See the README for links to the online installation guide, or install the compiler manually from either images/littleEndian or images/bigEndian'
  exit 1
fi

if [ "$prereqsUpgrade" != '' ]; then
  prereqsCommand="$prereqsUpgrade && $prereqsPrefix $prereqsCommand"
fi

if [ "$prereqsCommand" != '' ]; then
  echo "$prereqsCommand"
  eval $prereqsCommand
  rc=$?
  if [ $rc -ne 0 ]; then
    echo 'Installation of prerequisites failed, not installing compiler'
    exit 1
  fi
fi

if [ "$1" = "-R" ]
   then
    if [ "$ID_LIKE" = 'rhel' ]; then 
        installCommand="$sudo rpm -Uvh $root/images/rhel/cobol.rte*.rpm && $sudo rpm -Uvh --prefix=$2 $root/images/rhel/cobol.cmp*.rpm && $sudo rpm -Uvh $root/images/rhel/cobol.dbg*.rpm" 
    else
        echo 'Relocatable install only supported on RHEL'
        exit 1
    fi
fi

echo "$installCommand"
eval $installCommand
export PATH=$PATH:/bin:/usr/bin:/sbin:/usr/sbin:/opt/ibm/cobol/1.1.0/bin:/opt/ibm/cobol/debug/usr/bin/:/opt/ibm/cobol/1.1.0/usr/bin
export LD_LIBRARY_PATH=/opt/ibm/cobol/rte/lib
echo "PATH=$PATH:/bin:/usr/bin:/sbin:/usr/sbin:/opt/ibm/cobol/1.1.0/bin:/opt/ibm/cobol/debug/usr/bin/:/opt/ibm/cobol/1.1.0/usr/bin" >> ~/.bashrc
echo "LD_LIBRARY_PATH=/opt/ibm/cobol/rte/lib" >> ~/.bashrc
rc=$?

extendTrial="xlcmp_extend_eval xlcbl $(date +"%Y-%m-%d") && mv -f libxlcmpev_64r.so /opt/ibm/cobol/1.1.0/usr/lib/ && rm /opt/ibm/cobol/1.1.0/usr/bin/xlcmp_extend_eval"
eval $extendTrial

echo 'Installation and configuration successful'
exit $rc
